collections:
  projects:
    output: true
  services:
    output: true
  project-categories:
    output: true
  posts:
    output: true
    permalink: /:year/:month/:day/:title:output_ext

sass:
    sass_dir: _scss

categories:
  - aquatic-sports-and-leisure
  - commercial
  - educational
  - eco-tourism
  - guidelines-and-policy
  - sustainable-master-planning
  - residential
  - other
